apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sslvolume
spec:
  storageClassName: {{ .Values.storage.ssl.storageClass | quote }}
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.storage.ssl.size }}