apiVersion: v1
kind: Service
metadata:
  name: openemr
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.containerPorts.http }}
    - name: https
      port: {{ .Values.service.httpsPort }}
      targetPort: {{ .Values.containerPorts.https }}
  selector:
    name: openemr