apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-ui-cert
  namespace: longhorn-system
spec:
  secretName: longhorn-tls-secret
  duration: 87660h  # 10 years
  renewBefore: 360h
  privateKey:
    size: 2048
    algorithm: RSA
    encoding: PKCS1
  usages:
    - digital signature
    - key encipherment
    - server auth
  subject:
    organizations:
      - longhorn
  commonName: localhost
  dnsNames:
    - localhost
    - 127.0.0.1
    - longhorn-ui
    - longhorn-ui.longhorn-system
    - longhorn-ui.longhorn-system.svc
    - longhorn-ui.longhorn-system.svc.cluster.local
  issuerRef:
    name: ca-issuer
    kind: Issuer
    group: cert-manager.io
