#!/bin/sh

# first bring in cert-manager and allow enough time for it to set up
kubectl apply --validate=false -f https://github.com/cert-manager/cert-manager/releases/download/v1.11.0/cert-manager.yaml
echo "...waiting a minute to allow cert-manager to set up..."
sleep 60

kubectl apply \
    -f certs/selfsigned-issuer.yaml \
    -f certs/ca-certificate.yaml \
    -f certs/ca-issuer.yaml \
    -f certs/mysql.yaml \
    -f certs/mysql-openemr-client.yaml \
    -f certs/phpmyadmin.yaml \
    -f certs/mysql-phpmyadmin-client.yaml