image:
  registry: docker.io
  repository: bitnami/redis
  tag: 7.4.2-debian-12-r6

auth:
  enabled: true
  sentinel: true
  existingSecret: redis-secret
  existingSecretPasswordKey: redis-password

sentinel:
  enabled: true
  masterSet: mymaster
  quorum: 2
  resourcesPreset: nano
  ## resources:
  ##   requests:
  ##     cpu: 2
  ##     memory: 512Mi
  ##   limits:
  ##     cpu: 3
  ##     memory: 1024Mi
  ##

master:
  persistence:
    enabled: true
    storageClass: "standard"
    size: 8Gi
  resourcesPreset: micro
  ## resources:
  ##   requests:
  ##     cpu: 2
  ##     memory: 512Mi
  ##   limits:
  ##     cpu: 3
  ##     memory: 1024Mi
  ##
  
  # Change this part, if you want to adjust the port
  #service:
  #  type: ClusterIP
  #  port: 6379
  #containerPorts:
  #  mysql: 6379 
  #extraFlags:
  #  - "--port=6379" 
  
replica:
  replicaCount: 2
  persistence:
    enabled: true
    storageClass: "standard"
    size: 8Gi
  resourcesPreset: nano
  ## resources:
  ##   requests:
  ##     cpu: 2
  ##     memory: 512Mi
  ##   limits:
  ##     cpu: 3
  ##     memory: 1024Mi
  ##
 
  # Change this part, if you want to adjust the port
  #service:
  #  type: ClusterIP
  #  port: 6379
  #containerPorts:
  #  mysql: 6379 
  #extraFlags:
  #  - "--port=6379" 